# Exploratory Data Analysis for the crypto OHLCV data

In [1]:
import sys

sys.path.insert(0, "..")

import pandas as pd

from crypto_mlops import storage, utils

%load_ext autoreload
%autoreload 2

Change the `symbol` variable to load data for a different cryptocurrency pair.

**Note:** The data loading may take a few minutes if you are running it out of AWS region.

In [2]:
symbol = "BTC/USDT"
timeframe = "5m"

series_prefix = storage.get_series_prefix(symbol, timeframe)
dfs = storage.read_monthly_ohlcv(series_prefix)
df = pd.concat(dfs, ignore_index=True)

# Basic DataFrame Information

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 714853 entries, 0 to 714852
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   timestamp  714853 non-null  int64
 1   open       714853 non-null  float64
 2   high       714853 non-null  float64
 3   low        714853 non-null  float64
 4   close      714853 non-null  float64
 5   volume     714853 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 32.7 MB

In [4]:
df.head()

       timestamp     open     high      low    close     volume
0  1577836800000  7195.24  7196.25  7178.64  7179.78  95.509133
1  1577837100000  7179.76  7191.77  7178.20  7191.07  59.365225
2  1577837400000  7193.15  7193.53  7180.24  7180.97  48.068510
3  1577837700000  7180.97  7186.40  7177.35  7178.29  32.192929
4  1577838000000  7177.71  7182.46  7175.47  7176.96  49.027397

In [5]:
df.duplicated(subset=["timestamp"]).sum()

np.int64(0)

In [6]:
df.describe()

,timestamp,open,high,low,close,volume
count,7.148530e+05,714853.000000,714853.000000,714853.000000,714853.000000,714853.000000
mean,1.685185e+12,50299.681108,50350.280467,50248.265919,50299.783179,233.931945
std,6.193496e+10,30892.957264,30913.925312,30871.616670,30892.939145,411.980188
min,1.577837e+12,3888.650000,4094.250000,3782.130000,3882.220000,0.000000
25%,1.631578e+12,24066.450000,24105.520000,24024.750000,24066.320000,49.423200
50%,1.685204e+12,44243.070000,44305.560000,44181.320000,44243.060000,107.233230
75%,1.738818e+12,69465.430000,69519.700000,69412.900000,69465.580000,239.411410
max,1.792432e+12,126011.180000,126199.630000,125868.130000,126011.180000,15659.934840